export const languageStrings = {
  ja: {
    pageTitle: "先生・講師 新規登録 | D.Info",
    step1: "アカウント",
    stepDetails: [
      { title: "アカウント作成", subtitle: "基本情報を入力してください" },
      { title: "個人情報", subtitle: "個人情報を入力してください" },
      { title: "プロフィール", subtitle: "プロフィールを入力してください" },
      { title: "指導スキル", subtitle: "指導可能なスキルを選択してください" },
      { title: "レッスン詳細", subtitle: "レッスンの詳細を入力してください" },
      { title: "最終確認", subtitle: "入力内容を確認してください" },
    ],
    email: "メールアドレス",
    password: "パスワード",
    passwordConfirm: "パスワード（確認）",
    s1_title1: "ログイン情報",
    s1_title2: "住所情報",
    firstName: "名",
    lastName: "姓",
    prefecture: "都道府県",
    city: "市区町村",
    cityDisabledPlaceholder: "都道府県を選択してください",
    address: "住所",
    phone: "電話番号",
    phoneHelp: "ハイフンなしで入力してください\n例: 09012345678",
    nextBtn: "次へ",
    backBtn: "戻る",
    submitBtn: "登録",
    s2_title1: "個人情報",
    dob: "生年月日",
    gender: "性別",
    genderMale: "男性",
    genderFemale: "女性",
    genderOther: "その他",
    nationality: "国籍",
    nativeLang: "母国語",
    departureDate: "出国予定日",
    s2_title2: "身分証明書",
    idHelp: "身分証明書の表と裏の画像をアップロードしてください。",
    idFront: "身分証明書（表）",
    idBack: "身分証明書（裏）",
    s3_title1: "連絡先",
    email2: "予備メールアドレス",
    share_phone: "電話番号を公開",
    share_email2: "予備メールアドレスを公開",
    s3_title2: "プロフィール写真",
    profilePhoto: "プロフィール写真",
    photoHelp: "プロフィール写真は任意ですが、設定することをお勧めします。",
    s3_title3: "学歴・職歴",
    educationLevel: "最終学歴",
    major: "専攻",
    institutionName: "学校名",
    occupation: "職業",
    industry: "業界",
    occupationDetail: "職業詳細",
    s4_title1: "言語スキル",
    japaneseSkill: "日本語スキル",
    yearsInJapan: "日本在住年数",
    japanese_lesson_ok: "日本語でのレッスン可能",
    japanese_email_ok: "日本語でのメール連絡可能",
    lessonLang1: "指導言語1",
    isNative1: "ネイティブか",
    lessonLang2: "指導言語2",
    isNative2: "ネイティブか",
    teachingExperience: "指導経験",
    s4_title2: "指導内容",
    lessonTarget: "指導対象",
    targetAdult: "大人",
    targetSenior: "シニア",
    targetCollege: "大学生",
    targetHigh: "高校生",
    targetJuniorHigh: "中学生",
    targetElementary: "小学生",
    targetPreschooler: "幼児",
    lessonLevel: "指導レベル",
    levelBeginner: "初心者",
    levelNotSure: "よくわからない",
    levelReadWriteOk: "読み書きOK",
    levelShy: "恥ずかしがり屋",
    levelReturnee: "帰国子女",
    levelSpecializedLang: "専門言語",
    beginnerWelcome: "初心者歓迎",
    lessonTypesLabel: "レッスン形式",
    lessonTypeConversation: "会話",
    lessonTypeFreeTalk: "フリートーク",
    lessonTypeTravel: "旅行",
    lessonTypeCrossCulture: "異文化交流",
    lessonTypeBusiness: "ビジネス",
    lessonTypePronunciation: "発音",
    lessonTypeSlang: "スラング",
    lessonTypeRoleplay: "ロールプレイ",
    lessonTypeMedia: "メディア",
    lessonTypeNews: "ニュース",
    lessonTypeExamPrep: "試験対策",
    lessonTypeHomework: "宿題",
    lessonTypeKids: "子供向け",
    lessonTypeOriginalMaterials: "オリジナル教材",
    lessonTypeSpecialized: "専門",
    lessonTypeLangTest: "言語試験",
    lessonTypeCorporate: "企業向け",
    lessonTypeOther: "その他",
    testPrepLabel: "試験対策",
    testPrepToeic: "TOEIC",
    testPrepToefl: "TOEFL",
    testPrepBulats: "BULATS",
    testPrepEiken: "英検",
    testPrepGmat: "GMAT",
    testPrepIelts: "IELTS",
    testPrepCambridge: "ケンブリッジ",
    testPrepUn: "国連英検",
    testPrepIndustrial: "工業英検",
    testPrepTopec: "TOPEC",
    testPrepJhsExam: "中学校受験",
    testPrepHsExam: "高校受験",
    testPrepUniExam: "大学受験",
    engCertLabel: "英語資格",
    s5_title1: "レッスン料金",
    trialFee: "体験レッスン料金",
    privateFee: "プライベートレッスン料金",
    groupFee: "グループレッスン料金",
    onlineFee: "オンラインレッスン料金",
    s5_title2: "スケジュール",
    mon: "月",
    tue: "火",
    wed: "水",
    thu: "木",
    fri: "金",
    sat: "土",
    sun: "日",
    early_morning: "早朝",
    morning: "午前",
    lunchtime: "昼",
    afternoon: "午後",
    evening: "夕方",
    s5_title3: "レッスン場所",
    lessonArea: "レッスンエリア",
    selectAreaBtn: "エリアを選択",
    lessonStation: "最寄り駅",
    selectStationBtn: "駅を選択",
    lessonLocation: "レッスン場所",
    locationCafe: "カフェ",
    locationTeacherHome: "講師の自宅",
    locationStudentHome: "生徒の自宅",
    locationPark: "公園",
    locationPublic: "公共施設",
    landmark: "目印",
    landmarkHelp: "例: 新宿駅西口のスターバックス",
    stationNegotiable: "最寄り駅は相談可能",
    s6_title1: "趣味・興味",
    hobbies: "趣味",
    movies: "映画",
    music: "音楽",
    food: "食べ物",
    loveJapan: "日本で好きなこと",
    messageToStudent: "生徒へのメッセージ",
    s6_title2: "利用規約",
    termsLink: "利用規約",
    termsAgree: "に同意する",
    deleteRequest: "登録後に削除依頼が可能",
    areaModalTitle: "エリアを選択",
    stationModalTitle: "駅を選択",
    confirmBtn: "確定",
    region: "地域",
    prefecture: "都道府県",
    line: "路線",
    station: "駅",
    yes: "はい",
    no: "いいえ",
    selectPlaceholder: "選択してください",
  },
  en: {
    pageTitle: "Teacher Registration | D.Info",
    step1: "Account",
    stepDetails: [
      { title: "Create Account", subtitle: "Please enter your basic information" },
      { title: "Personal Information", subtitle: "Please enter your personal details" },
      { title: "Profile", subtitle: "Please enter your profile information" },
      { title: "Teaching Skills", subtitle: "Please select your teaching capabilities" },
      { title: "Lesson Details", subtitle: "Please provide lesson details" },
      { title: "Final Confirmation", subtitle: "Please review your information" },
    ],
    email: "Email Address",
    password: "Password",
    passwordConfirm: "Confirm Password",
    s1_title1: "Login Information",
    s1_title2: "Address Information",
    firstName: "First Name",
    lastName: "Last Name",
    prefecture: "Prefecture",
    city: "City",
    cityDisabledPlaceholder: "Please select a prefecture",
    address: "Address",
    phone: "Phone Number",
    phoneHelp: "Enter without hyphens\nExample: 09012345678",
    nextBtn: "Next",
    backBtn: "Back",
    submitBtn: "Register",
    s2_title1: "Personal Information",
    dob: "Date of Birth",
    gender: "Gender",
    genderMale: "Male",
    genderFemale: "Female",
    genderOther: "Other",
    nationality: "Nationality",
    nativeLang: "Native Language",
    departureDate: "Departure Date",
    s2_title2: "Identification",
    idHelp: "Please upload images of the front and back of your ID.",
    idFront: "ID (Front)",
    idBack: "ID (Back)",
    s3_title1: "Contact Information",
    email2: "Alternate Email",
    share_phone: "Share Phone Number",
    share_email2: "Share Alternate Email",
    s3_title2: "Profile Photo",
    profilePhoto: "Profile Photo",
    photoHelp: "A profile photo is optional but recommended.",
    s3_title3: "Education & Work",
    educationLevel: "Education Level",
    major: "Major",
    institutionName: "Institution Name",
    occupation: "Occupation",
    industry: "Industry",
    occupationDetail: "Occupation Details",
    s4_title1: "Language Skills",
    japaneseSkill: "Japanese Skill",
    yearsInJapan: "Years in Japan",
    japanese_lesson_ok: "Can teach in Japanese",
    japanese_email_ok: "Can communicate via email in Japanese",
    lessonLang1: "Teaching Language 1",
    isNative1: "Native Speaker?",
    lessonLang2: "Teaching Language 2",
    isNative2: "Native Speaker?",
    teachingExperience: "Teaching Experience",
    s4_title2: "Teaching Content",
    lessonTarget: "Target Students",
    targetAdult: "Adults",
    targetSenior: "Seniors",
    targetCollege: "College Students",
    targetHigh: "High School Students",
    targetJuniorHigh: "Junior High Students",
    targetElementary: "Elementary Students",
    targetPreschooler: "Preschoolers",
    lessonLevel: "Teaching Level",
    levelBeginner: "Beginner",
    levelNotSure: "Not Sure",
    levelReadWriteOk: "Can Read/Write",
    levelShy: "Shy Students",
    levelReturnee: "Returnees",
    levelSpecializedLang: "Specialized Language",
    beginnerWelcome: "Beginners Welcome",
    lessonTypesLabel: "Lesson Types",
    lessonTypeConversation: "Conversation",
    lessonTypeFreeTalk: "Free Talk",
    lessonTypeTravel: "Travel",
    lessonTypeCrossCulture: "Cross-Culture",
    lessonTypeBusiness: "Business",
    lessonTypePronunciation: "Pronunciation",
    lessonTypeSlang: "Slang",
    lessonTypeRoleplay: "Roleplay",
    lessonTypeMedia: "Media",
    lessonTypeNews: "News",
    lessonTypeExamPrep: "Exam Preparation",
    lessonTypeHomework: "Homework",
    lessonTypeKids: "Kids",
    lessonTypeOriginalMaterials: "Original Materials",
    lessonTypeSpecialized: "Specialized",
    lessonTypeLangTest: "Language Tests",
    lessonTypeCorporate: "Corporate",
    lessonTypeOther: "Other",
    testPrepLabel: "Test Preparation",
    testPrepToeic: "TOEIC",
    testPrepToefl: "TOEFL",
    testPrepBulats: "BULATS",
    testPrepEiken: "Eiken",
    testPrepGmat: "GMAT",
    testPrepIelts: "IELTS",
    testPrepCambridge: "Cambridge",
    testPrepUn: "UN English",
    testPrepIndustrial: "Industrial English",
    testPrepTopec: "TOPEC",
    testPrepJhsExam: "Junior High Exam",
    testPrepHsExam: "High School Exam",
    testPrepUniExam: "University Exam",
    engCertLabel: "English Certifications",
    s5_title1: "Lesson Fees",
    trialFee: "Trial Lesson Fee",
    privateFee: "Private Lesson Fee",
    groupFee: "Group Lesson Fee",
    onlineFee: "Online Lesson Fee",
    s5_title2: "Schedule",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    early_morning: "Early Morning",
    morning: "Morning",
    lunchtime: "Lunchtime",
    afternoon: "Afternoon",
    evening: "Evening",
    s5_title3: "Lesson Locations",
    lessonArea: "Lesson Area",
    selectAreaBtn: "Select Area",
    lessonStation: "Nearest Station",
    selectStationBtn: "Select Station",
    lessonLocation: "Lesson Location",
    locationCafe: "Cafe",
    locationTeacherHome: "Teacher's Home",
    locationStudentHome: "Student's Home",
    locationPark: "Park",
    locationPublic: "Public Facility",
    landmark: "Landmark",
    landmarkHelp: "Example: Starbucks at Shinjuku Station West Exit",
    stationNegotiable: "Station Negotiable",
    s6_title1: "Hobbies & Interests",
    hobbies: "Hobbies",
    movies: "Movies",
    music: "Music",
    food: "Food",
    loveJapan: "What You Love About Japan",
    messageToStudent: "Message to Students",
    s6_title2: "Terms of Service",
    termsLink: "Terms of Service",
    termsAgree: "I agree to the",
    deleteRequest: "Allow deletion request after registration",
    areaModalTitle: "Select Area",
    stationModalTitle: "Select Station",
    confirmBtn: "Confirm",
    region: "Region",
    prefecture: "Prefecture",
    line: "Line",
    station: "Station",
    yes: "Yes",
    no: "No",
    selectPlaceholder: "Please select",
  },
};

export const dropdownOptions = {
  educationLevelOptions: {
    ja: {
      "Compulsory": "義務教育",
      "High School": "高校",
      "Associate": "短期大学",
      "Bachelor": "大学",
      "Master": "修士",
      "Doctor": "博士",
    },
    en: {
      "Compulsory": "Compulsory",
      "High School": "High School",
      "Associate": "Associate",
      "Bachelor": "Bachelor",
      "Master": "Master",
      "Doctor": "Doctor",
    },
  },
  majorOptions: {
    ja: { none: "なし", science: "科学", arts: "芸術" },
    en: { none: "None", science: "Science", arts: "Arts" },
  },
  occupationOptions: {
    ja: { teacher: "教師", engineer: "エンジニア" },
    en: { teacher: "Teacher", engineer: "Engineer" },
  },
  industryOptions: {
    ja: { education: "教育", technology: "技術" },
    en: { education: "Education", technology: "Technology" },
  },
  japaneseSkillOptions: {
    ja: { none: "なし", beginner: "初級", intermediate: "中級", advanced: "上級" },
    en: { none: "None", beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" },
  },
  yearsInJapanOptions: {
    ja: { "0": "0年", "1-3": "1-3年", "3-5": "3-5年", "5+": "5年以上" },
    en: { "0": "0 years", "1-3": "1-3 years", "3-5": "3-5 years", "5+": "5+ years" },
  },
  lessonLangOptions: {
    ja: { none: "なし", english: "英語", spanish: "スペイン語" },
    en: { none: "None", english: "English", spanish: "Spanish" },
  },
  teachingExperienceOptions: {
    ja: { none: "なし", "1-2": "1-2年", "3-5": "3-5年", "5+": "5年以上" },
    en: { none: "None", "1-2": "1-2 years", "3-5": "3-5 years", "5+": "5+ years" },
  },
  trialFeeOptions: {
    ja: { "1000": "1000円", "2000": "2000円" },
    en: { "1000": "1000 JPY", "2000": "2000 JPY" },
  },
  privateFeeOptions: {
    ja: { "3000": "3000円", "4000": "4000円" },
    en: { "3000": "3000 JPY", "4000": "4000 JPY" },
  },
  groupFeeOptions: {
    ja: { none: "なし", "2000": "2000円" },
    en: { none: "None", "2000": "2000 JPY" },
  },
};

export const allPrefectures = {
  hokkaido: { ja: "北海道", en: "Hokkaido" },
  tokyo: { ja: "東京都", en: "Tokyo" },
  // Add other prefectures as needed
};

export const cityData = {
  hokkaido: { ja: ["札幌市", "函館市"], en: ["Sapporo", "Hakodate"] },
  tokyo: { ja: ["新宿区", "渋谷区"], en: ["Shinjuku", "Shibuya"] },
  // Add other cities as needed
};

export const stationData = {
  kanto: {
    ja: "関東",
    en: "Kanto",
    prefectures: {
      tokyo: {
        ja: "東京都",
        en: "Tokyo",
        lines: {
          yamanote: {
            ja: "JR山手線",
            en: "JR Yamanote Line",
            stations: [
              { ja: "東京", en: "Tokyo" },
              { ja: "新宿", en: "Shinjuku" },
            ],
          },
          // Add other lines as needed
        },
      },
      // Add other prefectures as needed
    },
  },
  // Add other regions as needed
};