// Dummy teacher data for list and profile pages
const teachers = [
  {
    id: '123404',
    name: 'Ash先生',
    price:'¥2,000',
    country: 'ジャマイカ',
    gender: '女性',
    age: '20代以下～30代前半',
    language: '英語・英会話 (ネイティブスピーカー)',
    area: '広島県福山市、尾道市、岡山県笠岡市、オンライン',
    profileImg: 'https://hello-sensei.com/sites/default/files/styles/340x340/public/imagefield_profile/2025/05/205455_123404/205455_123404_207438.jpeg?itok=qMlBOMRo',
    lastUpdated: '2025年05月21日',
    targetGroups: ['社会人、シニアの方', '大学生、高校生、中学生、小学生', '未就学児 (4歳以上)'],
    levels: ['英会話が全く初めての初心者の方', '基礎からしっかり学びたい方', '読み書きはできるけど会話が苦手な方', '留学・ワーホリ経験者、帰国子女の方', 'ビジネスシーンで使える英語を習得したい方', 'TOEIC、英検などの資格対策をしたい方'],
    favoriteLessons: ['日常英会話、旅行英会話', 'ビジネス英会話（メール、会議、プレゼンテーション）', 'TOEIC・英検などの試験対策', 'キッズ英会話（歌やゲームを取り入れた楽しいレッスン）', '発音矯正、リスニング強化', 'フリートーク、ディスカッション', '生徒様の希望に合わせたカスタマイズレッスン'],
    locations: ['カフェやレストラン (福山市駅周辺など)', '生徒様のご自宅 (家庭教師スタイル)', '公園など公共のスペース', 'Ash先生の自宅', 'オンラインレッスン対応！ (Zoom、Skypeなど)'],
    hiroshimaCities: [
      { name: '福山市', link: 'listc527.html?pref=hiroshima&city=fukuyama', stations: [{ id: 1, name: 'JR福山駅' }] },
      { name: '尾道市', link: 'list40ea.html?pref=hiroshima&city=onomichi', stations: [{ id: 2, name: 'JR尾道駅' }] }
    ],
    okayamaCities: [
      { name: '笠岡市', link: 'list4633.html?pref=okayama&city=kasaoka' }
    ],
    sanyoLineStations: [
      { name: '福山駅', link: 'list1b87.html?line=sanyo&station=fukuyama' },
      { name: '東福山駅', link: 'listf4e0.html?line=sanyo&station=higashi-fukuyama' },
      { name: '松永駅', link: 'list95f6.html?line=sanyo&station=matsunaga' },
      { name: '尾道駅', link: 'lista8cc.html?line=sanyo&station=onomichi' },
      { name: '笠岡駅', link: 'list1484.html?line=sanyo&station=kasaoka' }
    ],
    fukuenLineStations: [
      { name: '福山駅', link: 'list0dce.html?line=fukuen&station=fukuyama' },
      { name: '神辺駅', link: 'listf0a4.html?line=fukuen&station=kannabe' }
    ],
    preferredLocation: 'Fukuyama Train Station (福山駅) 周辺のカフェなど、ご相談に応じます。',
    nationality: 'ジャマイカ 🇯🇲',
    ageRange: '20代以下～30代前半',
    nativeLanguage: 'English (英語)',
    highestEducation: '４年制大学',
    major: '計算機科学',
    currentJob: '自由業（芸術家・音楽家etc）',
    japanStay: '6年～7年',
    japaneseLevel: '挨拶程度',
    qualifications: ['TESL/TEFL', 'DELTA'],
    teachingExperience: '7年～8年',
    features: '日本語でメール連絡が可能, 初心者大歓迎！',
    hobbies: ['コンテンツ制作', '旅行', 'ラグジュアリー体験', 'インスピレーションを受けること'],
    favoriteMovies: ['コメディ', '冒険', '感動する映画'],
    favoriteMusic: ['Socca', 'Reggae', 'R&B', 'afrobeat', 'K-pop'],
    favoriteFood: ['カリブ料理', 'オックステール', 'カレーゴート', 'ジャークチキン'],
    favoritePlaces: ['安全', '美味しい食べ物', '伝統と現代の融合'],
    trialPrice: 5000,
    manToManPrice: 5000,
    groupPrice: 4000,
    onlinePrice: 5000
  },
  {
    id: '124654',
    name: 'Areeba先生',
    country: 'パキスタン',
    price:'¥3,000',
    gender: '女性',
    age: '20代以下～30代前半',
    language: '英語・英会話',
    area: '千葉県山武郡',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月20日',
    targetGroups: ['中学生', '小学生'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常英会話', '試験対策'],
    locations: ['カフェ', '公園', '生徒宅', 'その他'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '千葉県山武郡周辺',
    nationality: 'パキスタン',
    ageRange: '20代以下～30代前半',
    nativeLanguage: '英語',
    highestEducation: '大学卒',
    major: '英語学',
    currentJob: '英語教師',
    japanStay: '1年未満',
    japaneseLevel: '日常会話',
    qualifications: ['TESOL'],
    teachingExperience: '1年～2年',
    features: '初心者歓迎, オンライン可',
    hobbies: ['読書', '映画鑑賞'],
    favoriteMovies: ['ロマンス', 'コメディ'],
    favoriteMusic: ['ポップ', 'クラシック'],
    favoriteFood: ['カレー', 'サモサ'],
    favoritePlaces: ['公園', 'カフェ'],
    trialPrice: 2000,
    manToManPrice: 2000,
    groupPrice: 1500,
    onlinePrice: 2000
  },
  {
    id: '126451',
    name: 'Bianca先生',
    country: 'フィリピン',
    gender: '女性',
    price:'¥4,000',
    age: '30代半ば～40代前半',
    language: 'フィリピン語, 英語・英会話',
    area: '東京都, 千葉県',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月19日',
    targetGroups: ['社会人', '高齢者', '大学生', '高校生', '中学生', '小学生', '未就学児'],
    levels: ['初心者', '中級者', '上級者'],
    favoriteLessons: ['日常英会話', 'ビジネス英会話'],
    locations: ['カフェ', '公園', '生徒宅', 'その他'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '東京都・千葉県内のカフェ',
    nationality: 'フィリピン',
    ageRange: '30代半ば～40代前半',
    nativeLanguage: 'フィリピン語',
    highestEducation: '大学卒',
    major: '教育学',
    currentJob: '英語教師',
    japanStay: '2年～3年',
    japaneseLevel: '日常会話',
    qualifications: ['TESOL'],
    teachingExperience: '10年以上',
    features: '初心者歓迎, オンライン可',
    hobbies: ['音楽', '旅行'],
    favoriteMovies: ['アクション', 'ドラマ'],
    favoriteMusic: ['J-POP', 'R&B'],
    favoriteFood: ['寿司', 'アドボ'],
    favoritePlaces: ['東京タワー', '浅草寺'],
    trialPrice: 3000,
    manToManPrice: 3000,
    groupPrice: 2500,
    onlinePrice: 3000
  },
  {
    id: '127001',
    name: 'Carlos先生',
    country: 'スペイン',
    gender: '男性',
    age: '30代前半',
    price:'¥3,000',
    language: 'スペイン語, 英語',
    area: '大阪府, 兵庫県',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月18日',
    targetGroups: ['社会人', '大学生'],
    levels: ['初心者', '中級者', '上級者'],
    favoriteLessons: ['日常会話', 'ビジネス会話'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '大阪市内のカフェ',
    nationality: 'スペイン',
    ageRange: '30代前半',
    nativeLanguage: 'スペイン語',
    highestEducation: '大学卒',
    major: '言語学',
    currentJob: '語学教師',
    japanStay: '3年～4年',
    japaneseLevel: '日常会話',
    qualifications: ['DELE', 'TESOL'],
    teachingExperience: '5年～6年',
    features: '明るくフレンドリー',
    hobbies: ['サッカー', '料理'],
    favoriteMovies: ['コメディ', 'アクション'],
    favoriteMusic: ['ラテン', 'ポップ'],
    favoriteFood: ['パエリア', 'タパス'],
    favoritePlaces: ['バルセロナ', '大阪城'],
    trialPrice: 2500,
    manToManPrice: 3000,
    groupPrice: 2000,
    onlinePrice: 2500
  },
  {
    id: '127002',
    name: 'Marie先生',
    country: 'フランス',
    gender: '女性',
    age: '20代後半',
    price:'¥2,000',
    language: 'フランス語, 英語',
    area: '東京都',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月17日',
    targetGroups: ['高校生', '社会人'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常会話', '旅行会話'],
    locations: ['カフェ', '生徒宅'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '渋谷・新宿周辺',
    nationality: 'フランス',
    ageRange: '20代後半',
    nativeLanguage: 'フランス語',
    highestEducation: '大学院卒',
    major: '教育学',
    currentJob: 'フリーランス教師',
    japanStay: '2年～3年',
    japaneseLevel: '簡単な会話',
    qualifications: ['DALF'],
    teachingExperience: '3年～4年',
    features: '丁寧な指導',
    hobbies: ['美術館巡り', 'カフェ巡り'],
    favoriteMovies: ['ドラマ', 'ロマンス'],
    favoriteMusic: ['シャンソン', 'クラシック'],
    favoriteFood: ['クレープ', 'チーズ'],
    favoritePlaces: ['パリ', '上野公園'],
    trialPrice: 3000,
    manToManPrice: 3500,
    groupPrice: 2500,
    onlinePrice: 3000
  },
  {
    id: '127003',
    name: 'John先生',
    country: 'アメリカ',
    gender: '男性',
    price:'¥4,000',
    age: '40代',
    language: '英語',
    area: '北海道札幌市',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月16日',
    targetGroups: ['社会人', '大学生', '高校生'],
    levels: ['初心者', '中級者', '上級者'],
    favoriteLessons: ['ビジネス英会話', '発音矯正'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '札幌駅周辺',
    nationality: 'アメリカ',
    ageRange: '40代',
    nativeLanguage: '英語',
    highestEducation: '大学卒',
    major: '経済学',
    currentJob: 'ビジネスコンサルタント',
    japanStay: '10年以上',
    japaneseLevel: 'ビジネス会話',
    qualifications: ['TESOL'],
    teachingExperience: '10年以上',
    features: 'ビジネス経験豊富',
    hobbies: ['登山', '写真'],
    favoriteMovies: ['サスペンス', 'ドキュメンタリー'],
    favoriteMusic: ['ロック', 'ジャズ'],
    favoriteFood: ['ハンバーガー', '寿司'],
    favoritePlaces: ['グランドキャニオン', '札幌'],
    trialPrice: 4000,
    manToManPrice: 4500,
    groupPrice: 3500,
    onlinePrice: 4000
  },
  {
    id: '127004',
    name: 'Anna先生',
    country: 'ロシア',
    gender: '女性',
    age: '30代後半',
    price:'¥6,000',
    language: 'ロシア語, 英語',
    area: '京都府',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月15日',
    targetGroups: ['大学生', '社会人'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常会話', '文法'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '京都市内',
    nationality: 'ロシア',
    ageRange: '30代後半',
    nativeLanguage: 'ロシア語',
    highestEducation: '大学院卒',
    major: '文学',
    currentJob: '翻訳者',
    japanStay: '5年～6年',
    japaneseLevel: '日常会話',
    qualifications: ['TESOL'],
    teachingExperience: '6年～7年',
    features: '親切で丁寧',
    hobbies: ['読書', 'ピアノ'],
    favoriteMovies: ['ドラマ', '歴史映画'],
    favoriteMusic: ['クラシック', 'ポップ'],
    favoriteFood: ['ボルシチ', '寿司'],
    favoritePlaces: ['モスクワ', '京都'],
    trialPrice: 3500,
    manToManPrice: 4000,
    groupPrice: 3000,
    onlinePrice: 3500
  },
  {
    id: '127005',
    name: 'Lina先生',
    country: 'ブラジル',
    price:'¥2,000',
    gender: '女性',
    age: '20代後半',
    language: 'ポルトガル語, 英語',
    area: '愛知県名古屋市',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月14日',
    targetGroups: ['小学生', '中学生'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常会話', 'キッズ英会話'],
    locations: ['カフェ', '生徒宅'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '名古屋駅周辺',
    nationality: 'ブラジル',
    ageRange: '20代後半',
    nativeLanguage: 'ポルトガル語',
    highestEducation: '大学卒',
    major: '教育学',
    currentJob: '英語教師',
    japanStay: '2年～3年',
    japaneseLevel: '簡単な会話',
    qualifications: ['TESOL'],
    teachingExperience: '2年～3年',
    features: '子供好き',
    hobbies: ['ダンス', '映画鑑賞'],
    favoriteMovies: ['アニメ', 'コメディ'],
    favoriteMusic: ['サンバ', 'ポップ'],
    favoriteFood: ['フェイジョアーダ', '寿司'],
    favoritePlaces: ['リオデジャネイロ', '名古屋城'],
    trialPrice: 2000,
    manToManPrice: 2500,
    groupPrice: 1500,
    onlinePrice: 2000
  },
  {
    id: '127006',
    name: 'David先生',
    country: 'イギリス',
    gender: '男性',
    price:'¥2,000',
    age: '50代',
    language: '英語',
    area: '神奈川県横浜市',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月13日',
    targetGroups: ['社会人', 'シニア'],
    levels: ['中級者', '上級者'],
    favoriteLessons: ['ビジネス英会話', '発音矯正'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '横浜駅周辺',
    nationality: 'イギリス',
    ageRange: '50代',
    nativeLanguage: '英語',
    highestEducation: '大学卒',
    major: '国際関係',
    currentJob: '英語講師',
    japanStay: '15年以上',
    japaneseLevel: '日常会話',
    qualifications: ['CELTA'],
    teachingExperience: '15年以上',
    features: '発音指導が得意',
    hobbies: ['ゴルフ', '読書'],
    favoriteMovies: ['歴史映画', 'サスペンス'],
    favoriteMusic: ['クラシック', 'ロック'],
    favoriteFood: ['フィッシュ＆チップス', 'ラーメン'],
    favoritePlaces: ['ロンドン', '横浜'],
    trialPrice: 5000,
    manToManPrice: 6000,
    groupPrice: 4000,
    onlinePrice: 5000
  },
  {
    id: '127007',
    name: 'Sophie先生',
    country: 'カナダ',
    gender: '女性',
    price:'¥2,000',
    age: '30代前半',
    language: '英語, フランス語',
    area: '福岡県',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月12日',
    targetGroups: ['高校生', '大学生'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常会話', '発音矯正'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '天神周辺',
    nationality: 'カナダ',
    ageRange: '30代前半',
    nativeLanguage: '英語',
    highestEducation: '大学卒',
    major: '心理学',
    currentJob: '英語教師',
    japanStay: '4年～5年',
    japaneseLevel: '日常会話',
    qualifications: ['TESOL'],
    teachingExperience: '5年～6年',
    features: '明るく親しみやすい',
    hobbies: ['旅行', '写真'],
    favoriteMovies: ['コメディ', 'ドラマ'],
    favoriteMusic: ['ポップ', 'カントリー'],
    favoriteFood: ['プーティン', '寿司'],
    favoritePlaces: ['モントリオール', '福岡'],
    trialPrice: 3000,
    manToManPrice: 3500,
    groupPrice: 2500,
    onlinePrice: 3000
  },
  {
    id: '127008',
    name: 'Chen先生',
    country: '中国',
    price:'¥2,000',
    gender: '男性',
    age: '40代',
    language: '中国語, 英語',
    area: '埼玉県',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月11日',
    targetGroups: ['社会人', '大学生'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常会話', 'ビジネス会話'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '大宮駅周辺',
    nationality: '中国',
    ageRange: '40代',
    nativeLanguage: '中国語',
    highestEducation: '大学院卒',
    major: '経営学',
    currentJob: '中国語講師',
    japanStay: '8年～9年',
    japaneseLevel: '日常会話',
    qualifications: ['HSK', 'TESOL'],
    teachingExperience: '8年～9年',
    features: 'ビジネス中国語対応',
    hobbies: ['囲碁', '読書'],
    favoriteMovies: ['歴史映画', 'アクション'],
    favoriteMusic: ['ポップ', '伝統音楽'],
    favoriteFood: ['火鍋', '寿司'],
    favoritePlaces: ['上海', '大宮'],
    trialPrice: 3500,
    manToManPrice: 4000,
    groupPrice: 3000,
    onlinePrice: 3500
  },
  {
    id: '127009',
    name: 'Fatima先生',
    country: 'エジプト',
    gender: '女性',
    age: '30代半ば',
    price:'¥2,000',
    language: 'アラビア語, 英語',
    area: '京都府',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月10日',
    targetGroups: ['社会人', '大学生'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常会話', '旅行会話'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '京都駅周辺',
    nationality: 'エジプト',
    ageRange: '30代半ば',
    nativeLanguage: 'アラビア語',
    highestEducation: '大学卒',
    major: '英語学',
    currentJob: '英語教師',
    japanStay: '3年～4年',
    japaneseLevel: '簡単な会話',
    qualifications: ['TESOL'],
    teachingExperience: '4年～5年',
    features: '親しみやすい',
    hobbies: ['料理', '旅行'],
    favoriteMovies: ['ドラマ', 'コメディ'],
    favoriteMusic: ['アラビック', 'ポップ'],
    favoriteFood: ['コシャリ', '寿司'],
    favoritePlaces: ['カイロ', '京都'],
    trialPrice: 2500,
    manToManPrice: 3000,
    groupPrice: 2000,
    onlinePrice: 2500
  },
  {
    id: '127010',
    name: 'Marta先生',
    country: 'ポーランド',
    gender: '女性',
    age: '20代後半',
    language: 'ポーランド語, 英語',
    area: '東京都',
    price:'¥2,000',
    profileImg: 'https://placehold.co/120x120/E2E8F0/A0AEC0?text=Teacher',
    lastUpdated: '2025年05月09日',
    targetGroups: ['高校生', '大学生'],
    levels: ['初心者', '中級者'],
    favoriteLessons: ['日常会話', '発音矯正'],
    locations: ['カフェ', 'オンライン'],
    hiroshimaCities: [],
    okayamaCities: [],
    sanyoLineStations: [],
    fukuenLineStations: [],
    preferredLocation: '新宿・池袋周辺',
    nationality: 'ポーランド',
    ageRange: '20代後半',
    nativeLanguage: 'ポーランド語',
    highestEducation: '大学卒',
    major: '言語学',
    currentJob: '英語教師',
    japanStay: '2年～3年',
    japaneseLevel: '簡単な会話',
    qualifications: ['TESOL'],
    teachingExperience: '2年～3年',
    features: '明るく元気',
    hobbies: ['映画鑑賞', '旅行'],
    favoriteMovies: ['コメディ', 'ドラマ'],
    favoriteMusic: ['ポップ', 'ロック'],
    favoriteFood: ['ピエロギ', '寿司'],
    favoritePlaces: ['ワルシャワ', '東京'],
    trialPrice: 2000,
    manToManPrice: 2500,
    groupPrice: 1500,
    onlinePrice: 2000
  }
];

export default teachers; 